### ISSUE TITLE
filter tab is broken

### ISSUE THREAD

**Issue by grixxxx** [ASWAN123/To-Do-List-App#1]
filter tab is broken try to use `flexbox` or `grid` property and the delete button is `div` tag change it into `button` tag 

![Screenshot 2022-12-23 at 20-37-36 TodoList App](https://user-images.githubusercontent.com/110141187/209338106-d8d0a17e-b50a-4013-b308-6340ee89345a.png)

**Comment by ASWAN123** [comment]
are you talking about the mobile version because its starts from 375px  .

**Comment by grixxxx** [comment]
> 

yes, on mobile view its broken

**Comment by ASWAN123** [comment]
okay thank you so  much  i will fix  it .

**Comment by ASWAN123** [comment]
the  issue  has been fixed  , thanks
